COLUMNS:
  Car_Name: str
  Year: int64
  Selling_Price: float64
  Present_Price: float64
  Kms_Driven: int64
  Fuel_Type: str
  Seller_Type: str
  Transmission: str
  Owner: int64

TARGET_COLUMN:
  name: Selling_Price